project:
  type: book
  output-dir: _output
  resources:
  - ./assets/**
  - '!materials/**'
  - '!**/_*.qmd'
profile:
  default: student
  group:
  - - student
    - full
course:
  id: cybersecurity-theory
  validate: true
filters:
- course-core
- course-presentation
course-presentation:
  mode: study
book:
  sidebar:
    tools:
    - icon: house
      href: ../index.html#sec-portal
      text: Навигация курса
  title: Теория
  chapters:
  - index.qmd
  - part: Криптография
    chapters:
    - crypto/random.qmd
    - crypto/hash.qmd
    - crypto/key-gen.qmd
    - crypto/cypher.qmd
format:
  html:
    theme: cosmo
    html-math-method:
      method: mathjax
lang: ru
author:
- Афоненко Анатолий
- Лайша Богдан
bibliography: references.bib
engine: knitr
