project:
  output-dir: _output/full
course:
  view: full
book:
  chapters:
  - index.qmd
  - part: Криптография
    chapters:
    - crypto/random.qmd
    - crypto/hash.qmd
    - crypto/key-gen.qmd
    - crypto/cypher.qmd
