project:
  type: book
  output-dir: _output
  resources:
  - ./assets/**
  - '!materials/**'
  - '!**/*.qmd'
  - '!_generated/**'
  - '!_freeze/**'
  - '!.quarto/**'
  pre-render:
  - _extensions/Afonenko-Course-Tools/course-core/entrypoints/pre.ts
  post-render:
  - _extensions/Afonenko-Course-Tools/course-core/entrypoints/post.ts
  - _extensions/Afonenko-Course-Tools/reference-catalog/entrypoints/post.ts
  - ../_extensions/Afonenko-Course-Tools/course-site/entrypoints/collect.ts
profile:
  default: student
  group:
  - - student
    - full
course:
  id: cybersecurity-theory
filters:
- course-core
- course-presentation
- reference-catalog
course-presentation:
  mode: study
book:
  sidebar:
    tools:
    - icon: house
      href: ../index.html#sec-portal
      text: Навигация курса
  title: Теория
  chapters:
  - index.qmd
  - part: Криптография
    chapters:
    - crypto/random.qmd
    - crypto/hash.qmd
    - crypto/key-gen.qmd
    - crypto/cypher.qmd
format:
  html:
    theme: cosmo
    html-math-method:
      method: mathjax
lang: ru
author:
- Афоненко Анатолий
bibliography: references.bib
engine: knitr
reference-catalog:
  namespace: theory
