project:
  type: default
  render:
  - index.qmd
  - sessions/1.qmd
  - sessions/2.qmd
  - sessions/3.qmd
  - sessions/4.qmd
  - sessions/5.qmd
  - sessions/6.qmd
  - sessions/7.qmd
  - sessions/8.qmd
  output-dir: _output
  resources:
  - ./assets/**
  - '!materials/**'
  - '!**/*.qmd'
  - '!**/_*.qmd'
  - '!_generated/**'
  - '!_freeze/**'
  - '!.quarto/**'
  - '!_extensions/**'
  pre-render:
  - _extensions/Afonenko-Course-Tools/course-core/entrypoints/pre.ts
  post-render:
  - _extensions/Afonenko-Course-Tools/course-core/entrypoints/post.ts
  - _extensions/Afonenko-Course-Tools/reference-catalog/entrypoints/post.ts
  - ../_extensions/Afonenko-Course-Tools/course-site/entrypoints/collect.ts
profile:
  default: student
  group:
  - - student
    - full
course:
  id: cybersecurity-practice
filters:
- course-core
- course-presentation
- reference-catalog
course-presentation:
  mode: study
format:
  revealjs:
    shift-heading-level-by: -1
    slide-level: 2
    navigation-mode: linear
    theme: default
    show-notes: false
    slide-number: true
    revealjs-plugins:
    - course-navigation
lang: ru
reference-catalog:
  namespace: practice
