project:
  output-dir: _output/student
course:
  view: student
book:
  chapters:
  - index.qmd
  - part: Криптография
    chapters:
    - crypto/random.qmd
    - crypto/hash.qmd
    - crypto/cypher/symmetric.qmd
    - crypto/cypher/asymmetric.qmd
    - crypto/sign.qmd
    - crypto/cert.qmd
  - part: Управление доступом
    chapters:
    - access-control/ident.qmd
    - access-control/authn.qmd
    - access-control/authz.qmd
  - part: Целостность данных
    chapters:
    - data-integrity/backup.qmd
  - part: Семминары
    chapters:
    - seminar/01-introduction.qmd
    - seminar/02-structure.qmd
