project:
  output-dir: _output/student
course:
  view: student
book:
  chapters:
  - index.qmd
  - plans/index.qmd
  - part: Криптография
    chapters:
    - seminar/crypto/random.qmd
    - seminar/crypto/hash.qmd
    - seminar/crypto/cypher/symmetric.qmd
    - seminar/crypto/cypher/asymmetric.qmd
    - seminar/crypto/sign.qmd
    - seminar/crypto/cert.qmd
  - part: Управление доступом
    chapters:
    - seminar/access-control/ident.qmd
    - seminar/access-control/authn.qmd
    - seminar/access-control/authz.qmd
  - part: Целостность данных
    chapters:
    - seminar/data-integrity/backup.qmd
