---
assessment:
  kind: lab
---

# Идентификация {#sec-work-access-control-ident}

## Практические действия {#sec-lab-access-control-ident}

::: {#exr-lab-access-control-ident course-role="independent-study" difficulty="introductory"}
### Условие работы

Определить и подготовить отчёт в виде таблицы `.csv` для последующего отправления. <https://habr.com/ru/articles/685020/>

#### Браузер

Логин eduroam

С помощью инструментов разработчика или расширения по типу Cookie Viewer определить свои идентификаторы на сайтах 21vek, 5 элемент, озон, вб и д.р.

#### Система

Для всех систем серийный номер процессора, материнской платы, диска. MAC аддрес.

##### Windows

Серийник процессора из MSDN. Machine GUID `win32_computerproduct`

```         
(Get-CimInstance -Class Win32_ComputerSystemProduct)
```

Коды устройств из Device Manager

[[https://www.reddit.com/r/sysadmin/comments/6it3u2/windows_os_unique_identifier/]{.underline}](https://www.reddit.com/r/sysadmin/comments/6it3u2/windows_os_unique_identifier/ "https://www.reddit.com/r/sysadmin/comments/6it3u2/windows_os_unique_identifier/")

##### Linux

-   Machine ID `/etc/machine-id`
-   System UUID `/sys/class/dmi/id/product_uuid` или `dmidecode -s system-uuid`
-   `lspci`: Lists PCI devices and their IDs.
-   `blkid`: Identifies block devices and their UUIDs/PARTUUIDs.

Разные идентификатор, куки и как их посмпотреть, а также другие системные Определить свой идентификатор на андроиде

Проверка — уникальность + соответствие формату.

#### Android

Определить свои рекламные ID
:::

::: {.assessment-items}
1. @exr-lab-access-control-ident
:::
