---
assessment:
  kind: lab
---

# Генерация случайных чисел {#sec-work-crypto-rng}

## Практические действия {#sec-lab-crypto-rng}

::: {#exr-lab-crypto-rng course-role="independent-study" difficulty="introductory"}
### Условие работы

@theory:sec-theory-crypto-random

Используя криптографически стойкий генератор случайных чисел получить файл из случайных чисел / последовательностей, закодировать его в base64 для удобного представления и пересылки. Для linux использовать источник `/dev/random`. Для винды использовать криптографичесоке API вызов через PowerShell

Способ вызвать dotnet из скрипта PowerShell <https://stackoverflow.com/questions/31250864/how-do-i-get-truly-random-numbers-in-batch>

Актуальное API по ссылке <https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.randomnumbergenerator?view=net-9.0>

Проверить генератор случайных чисел статистическими тестами <https://www.pcg-random.org/posts/how-to-test-with-practrand.html> Для этого надо собрать PractRand из исходников. Для винды будет предоставлен предварительно собранный exe для линукса пусть собирают ручками <https://gitlab.com/arbitrand/arbitrand-public/-/tree/main?ref_type=heads>
:::

::: {.assessment-items}
1. @exr-lab-crypto-rng
:::
